@echo off
copy Zen_StandardLibrary.sqf Zen_DataFunctions
copy Zen_StandardLibrary.sqf Zen_DialogSystem
copy Zen_StandardLibrary.sqf Zen_FireSupportSystem
copy Zen_StandardLibrary.sqf Zen_LoadoutFunctions
copy Zen_StandardLibrary.sqf Zen_MathFunctions
copy Zen_StandardLibrary.sqf Zen_MiscFunctions
copy Zen_StandardLibrary.sqf Zen_ObjectFunctions
copy Zen_StandardLibrary.sqf Zen_ObjectiveSystem
copy Zen_StandardLibrary.sqf Zen_OrdersFunctions
copy Zen_StandardLibrary.sqf Zen_PositionFunctions
copy Zen_StandardLibrary.sqf Zen_SpawningFunctions
copy Zen_StandardLibrary.sqf Zen_TaskSystem
copy Zen_StandardLibrary.sqf Zen_TriggerFunctions
copy Zen_FrameworkLibrary.sqf Zen_DataFunctions
copy Zen_FrameworkLibrary.sqf Zen_DialogSystem
copy Zen_FrameworkLibrary.sqf Zen_FireSupportSystem
copy Zen_FrameworkLibrary.sqf Zen_LoadoutFunctions
copy Zen_FrameworkLibrary.sqf Zen_MathFunctions
copy Zen_FrameworkLibrary.sqf Zen_MiscFunctions
copy Zen_FrameworkLibrary.sqf Zen_ObjectFunctions
copy Zen_FrameworkLibrary.sqf Zen_ObjectiveSystem
copy Zen_FrameworkLibrary.sqf Zen_OrdersFunctions
copy Zen_FrameworkLibrary.sqf Zen_PositionFunctions
copy Zen_FrameworkLibrary.sqf Zen_SpawningFunctions
copy Zen_FrameworkLibrary.sqf Zen_TaskSystem
copy Zen_FrameworkLibrary.sqf Zen_TriggerFunctions
echo Framework and Standard libraries copied to all framework folders
pause
exit
