//Briefing example used in a video tutorial by Feuerex;
//It's best to use init.sqf, but any script will do. Just make sure to launch it.;

player createDiaryRecord["Diary", ["the basics", "At mission start and after respawnyou will see MISSION CONTROL on your action menu.<br/>This is where you get all important info about the current game state.<br/>Once your commander has built your base you will see several BASE BUILDINGS.<br/>Purchase vehicles and upgrades at these.<br/>If you are not the COMMANDER then get into the MCU (Mobile Construction Vehicle) in the back.<br/>DO NOT GET IN AS DRIVER UNLESS YOU ARE THE COMMANDER.<br/>The MCU is vital to your teams chances of winning since it is used to create your base."]];
player createDiaryRecord["Diary", ["RTS3", "ported from ofp<br/><br/>OPERATION FLASHPOINT 2003"]];
player creatediarysubject ["FIRST GOAL","FIRST GOAL"];
player createDiaryRecord["FIRST GOAL", ["SECURE TERRITORY", "Remember that capturing territories near to your base first<br/>may give your posistion away to the enemy.<br/>Each territory you capture will turn the color of your team<br/>Gray for Unoccupied<br/>Blue for NATO<br/>Red for the SOVIETS.<br/>To capture a territory<br/>you DO NOT take flags<br/>Instead you must occupy a territory<br/>with more soldiers than the enemy.<br/>Each territory has a small dark square marker.<br/>This is the<br/>Control Zone<br/>You must occupy that area for<br/>a certain period of time to take control.<br/>If either team is present,<br/>then a marker will show SOVIET or NATO prescence in that control zone.<br/>Your team must have more soldiers in<br/>the territory to take control from the enemy.<br/>If the territory is already controlled by the enemy,<br/>then it will take longer to change control to your team."]];
player creatediarysubject ["2nd GOAL","2nd GOAL"];
player createDiaryRecord["2nd GOAL", ["FIND THE ENEMY BASE", "Now that you have captured some territories<br/>and are earning money for your team,<br/>it is time to find the enemy base<br/>so you can begin planning to destroy it.<br/>This is best accomplished by purchasing a cheap air like<br/>the CIV Heli and scouting out the island.<br/>Make sure to place a marker over the enemy base<br/>on the map should you find it first."]];
player creatediarysubject ["DEFENSE","DEFENSE"];
player createDiaryRecord["DEFENSE", ["DEFENSE", "Rather than scouting for the enemy,<br/>you may choose to stay at the base<br/>and help secure it.<br/>You can train AI and place them in Armored AA vehicles,<br/>or you could purchase a Construction Jeep<br/>and build SAM's and place AI in them.<br/>Keep a close eye on the map<br/>because the Radar Tower will help a lot."]];
player creatediarysubject ["CREDITS","CREDITS"];
player createDiaryRecord["CREDITS", ["CREDITS TO", ""]];