private "_return";

_return =
[
    "ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\ManSlay_Class.sqf",
	"ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\Man_Class.sqf",
	"ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\Cars_Class.sqf",
	"ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\Tanks_Class.sqf",
	"ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\Air_Class.sqf",
	"ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\Helicopter_Class.sqf",
	"ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\Plane_Class.sqf",
	"ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\Static_Class.sqf",
	"ROTATION_MENU_SYSTEM\DEFAULT_CLASSES\Ship_Class.sqf"
];

_return;
